### PR TITLE
PanelThemePicker Component 🎈

### PR DESCRIPTION
**Pull request by mahdiyazdani**
This PR introduces a new React component that renders an Inspector UI panel and allows users to select the desired skin from the options available.

Screen Shot 2021-10-31 at 8 47 24 PM

### CODE REVIEW

**Review by kuserich — APPROVED** [review]
Thank you, @mahdiyazdani

**Review by gooklani — APPROVED** [review]
Thank you @mahdiyazdani, since we want to reuse it in other blocks like Instagram, wouldn’t it be better to have a different name?

**Comment by mahdiyazdani** [comment]
@gooklani I’m open to suggestions? @kuserich Do you have any potential name(s) to propose?

**Comment by gooklani** [comment]
> @gooklani I’m open to suggestions? @kuserich Do you have any potential name(s) to propose?

Thank you 😊, @mahdiyazdani @kuserich What do you think about `Block theme` or `Block layout`?

**Comment by kuserich** [comment]
> > @gooklani I’m open to suggestions? @kuserich Do you have any potential name(s) to propose?
> 
> Thank you 😊, @mahdiyazdani @kuserich What do you think about `Block theme` or `Block layout`?

Given that the component is indeed a `Picker` I believe the name should include the word. Similarly, using `Theme` or `Layout` is equally incorrect for skins as `Skin` is for layouts 😄 . IMO, the essence of the component is the ability to select the visual appearance from a preview (rather than what type of visual appearance it is) and my proposal would thus be `PanelPreviewPicker`.

If you disagree with that proposal, I would be fine with using `Theme` or `Layout` as well (i.e. `PanelThemePicker` and `PanelLayoutPicker`).

**Comment by gooklani** [comment]
@mahdiyazdani @kuserich My vote is `PanelThemePicker` 😊

**Comment by mahdiyazdani** [comment]
I have renamed the component as per your suggestion @gooklani @kuserich. Please feel free to review the updated code. 🙂

**Review by gooklani — APPROVED** [review]
Awesome 👏 , thank you @mahdiyazdani

**Review by kuserich — APPROVED** [review]
Nice, thank you @mahdiyazdani

**Pull request merged**
